# Création de l'image BDD Mysql pour LogicalDoc
FROM mysql:5.7

# Informations sur l'image à créer
LABEL maintener="autom2.groupe1@henix.fr" Description="Image mysql:5.7 avec les scripts de création de la BDD et du user et de peuplement pour LogicalDoc" tag="mysql:5.7"

# Variables d'environnement des scripts de création et le peuplement de la BDD et divers
ENV BDD_SERVICE         mysql
ENV BDD_INIT_SH         init_bdd_${BDD_SERVICE}.sh
ENV BDD_INIT_SQL        init_bdd_${BDD_SERVICE}.sql
ENV BDD_INIT_DUMP       logicaldoc_${BDD_SERVICE}.sql
#
ENV WAIT_HERE_SH        wait_here.sh

# Variables d'environnement pour la création et le peuplement de la BDD
ENV DB_NAME             logicaldoc
ENV DB_USER             ldoc
ENV DB_PASSWORD         password
ENV MYSQL_ROOT_PASSWORD password

# Installation des packages nécessaires
RUN apt-get update; apt-get install -y sudo vim

# Nettoyage des packages obsolètes
RUN apt-get autoclean autoremove

# Exposition à l'extérieur du port 3306 du conteneur
EXPOSE 3306

# Récupération dans WORKDIR=/tmp des scripts définis plus haut
WORKDIR /tmp
COPY ${BDD_INIT_SQL} .
COPY ${BDD_INIT_SH} .
COPY ${BDD_INIT_DUMP} .
COPY ${WAIT_HERE_SH} .

# Ajout des droits d'exécution aux scripts SHELL
RUN chmod +x ${BDD_INIT_SH} ${WAIT_HERE_SH}

# Lancement du moteur de BDD, création de la BDD et du USER, puis peuplement de la BDD 
CMD service ${BDD_SERVICE} start && cd /tmp && ./${BDD_INIT_SH} && ./${WAIT_HERE_SH}
